ex:		main.cpp  Arc.cpp  Arc.hpp
		g++ -Wno-deprecated -I/usr/local/include -I/usr/include/freetype2 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT -o 'ex' 'main.cpp' 'Arc.cpp'  /home/blanca/bs_ppp/bs_fltk/Graph.cpp /home/blanca/bs_ppp/bs_fltk/GUI.cpp /home/blanca/bs_ppp/bs_fltk/Simple_window.cpp /home/blanca/bs_ppp/bs_fltk/Window.cpp  /usr/local/lib/libfltk_images.a -lpng -lz -ljpeg /usr/local/lib/libfltk.a -lXext -lXft -lfontconfig -lXinerama -lpthread -ldl -lm -lX11 


