rc:		calc.o  Roman_int.o
		g++ -g -Wall -ansi  calc.o  Roman_int.o  -o rc

calc.o:		calc.cpp  Roman_int.hpp
		g++ -g -Wall -ansi -c  calc.cpp  -o calc.o

Roman_int.o:	Roman_int.cpp  Roman_int.hpp
		g++ -g -Wall -ansi -c  Roman_int.cpp  -o Roman_int.o
